### PR TITLE
Support @class and @constructor jsdoc attributes

### PR DESCRIPTION
**Pull request by Rantanen**
http://usejsdoc.org/tags-class.html

`@class` and `@constructor` behave the same as `@this`, but unlike `@this`, which needs an explicit type name, these two attributes define the 'this' parameter as the current function without having to implicitly name it.

Only the default syntax without explicit type/name is supported.

### CODE REVIEW

**Comment by marijnh** [comment]
Should `this` really refer to the constructor function in this case? The way I understand it, it should be pointing at an instance of that constructor (i.e. an object derived from its `prototype` property).

**Comment by Rantanen** [comment]
Doesn't the `parseType` take care of that?

```
/** @param {Foo} f */
var method = function(f) {
  // f is instance of 'Foo'
}

/** @class */
var Foo = function() {
  // 'this' is instance of 'Foo'
}
```

.. or then I'm completely failing at jsdoc. Will look whether I'll figure out how the jsdoc type definitions work with self defined types.

**Comment by marijnh** [comment]
I'm going by your tests, which assert the type of this to be `fn()`, which looks suspicious.

**Comment by Rantanen** [comment]
Oh right. That one.

I admit that confused me as well, but figured that was some acorn-specific detail that I didn't understand.

Did more testing. Apparently somewhere there is code that compares the case of the function. 'abc' -> fn(), 'Abc' -> Abc. Fixed tests.

**Comment by marijnh** [comment]
Ah, I see what was going on now -- because the constructors weren't capitalized, the parseType didn't treat them as constructors. I've pushed a somewhat robust implementation in d45e911, and merged your tests in 1ac35c058b2

**Pull request closed without merging**
