### PR TITLE
Fix `Cannot read property 'prev' of null`

### PR DESCRIPTION
**Pull request by jfelsinger**
Not sure if this is the correct way to do this, but it fixed the bug that I was seeing locally with auto-completion and all that.

Should be a fix for: #891

### CODE REVIEW

**Comment by marijnh** [comment]
That doesn't really address the underlying issue, though. I'd prefer to see an example of how to reproduce it so that I can properly fix it.

**Comment by guiguan** [comment]
This issue can be reproduced with `atom-ternjs` package. Probably @jfelsinger can provide a concrete example?

**Comment by lyjstudy** [comment]
FIXED: https://github.com/lyjstudy/tern
rmScope will destroy node.scope, so we cache it

**Comment by marijnh** [comment]
Solved via #905

**Pull request closed without merging**
