### PR TITLE
support webpack.config.js for webpack plugin

### PR DESCRIPTION
**Pull request by chemzqm**
This PR use latest `enhanced-resolve` module, supports:
* Load `webpack.config.js` from the same folder
* Same default options as webpack itself.
* Configuration like `root` `alias` `packageMains ` etc.
* es6 `import` support by using `es_modules` plugin.

### CODE REVIEW

**Comment by marijnh** [comment]
Looks good. Could you add a few tests to make sure future changes don't end up breaking this?

**Comment by karlhorky** [comment]
Would it make sense to make the configuration file name configurable?

**Comment by marijnh** [comment]
Thanks! Merged as a5a5ba61ae3a5...b445a26a85e3349

(If the answer to @karlhorky 's question is yes, let's create a different issue or PR for that.)

**Comment by chemzqm** [comment]
@karlhorky added in #807

**Comment by karlhorky** [comment]
Awesome, nice one @chemzqm

**Pull request closed without merging**
