### PR TITLE
All proposals shown inside string literal #780

### PR DESCRIPTION
**Pull request by mrennie**
https://github.com/ternjs/tern/issues/780

If there are no loaded plugins that handle completions inside literals, we should return none.

Related Orion bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=492470

### CODE REVIEW

**Comment by marijnh** [comment]
This is something that I think you should solve on the client side. Or, if that's difficult, add this as a query option that defaults to false. I want the default behavior to stay what it is now.

**Comment by mrennie** [comment]
Ok, I'll update the pull request to add a query flag. Any particular name you would prefer for the new flag?

**Comment by marijnh** [comment]
`inLiterals: false` sounds like a descriptive name (where anything non-false counts as true).

**Comment by mrennie** [comment]
I'm going to close this pull request and open a new one - to avoid the merge commit.

**Pull request closed without merging**
