### PR TITLE
When we try to define style for Nodes the hint is not showing up for style

### PR DESCRIPTION
**Pull request by NehaModi**
Changes re done to show the hints for style when defines for Node in the same way as we define for elements

### CODE REVIEW

**Comment by othree** [comment]
I know your issue.
But style belongs to `Element` not `Node`.

I prefer replace all returned `+Node` to `+Element` instead of add style to Node, which only adds `style`.

**Comment by NehaModi** [comment]
I have replaced +Node to +element. We have to address this Bug for parentNode ,so I have replaced there.

**Comment by NehaModi** [comment]
ping @othree

**Comment by othree** [comment]
Hi, Sorry I do not reply at the time you send the following commit.

Could update the commit message to meaningful description.

Maybe something like:

> parentNode returns +Element instead of +Node for better usability.

**Comment by NehaModi** [comment]
Hi,
I have changed the commit message as per requirement.Please look into it

**Comment by NehaModi** [comment]
Ping @othree

**Comment by othree** [comment]
Thank you !

**Pull request merged**
