### PR TITLE
Allow for webpack function configs

### PR DESCRIPTION
**Pull request by eloytoro**
Webpack allows configs to be functions, this would enable support for that

### CODE REVIEW

**Comment by chemzqm** [comment]
Looks good, didn't notice there's function config.

**Comment by eloytoro** [comment]
Decided to add the ability to just pass the modules you're trying to resolve.
My webpack config does some heavy computing by just requiring it and it was causing lots of lag.
I think its great to have it for simplicity as well

**Comment by chemzqm** [comment]
@eloytoro the `modules` are folder for resolve modules, which is just node_modules most of case, why your webpack need computed for that?

**Comment by eloytoro** [comment]
remember we're loading the entire webpack config, my project is quite big and the config has a lot of dependencies, thus requiring the config means requiring a bunch of stuff and sometimes that means heavy computation.

> which is just node_modules most of case

This is, as far as as I've seen, in practice not accurate, most projects have more than one resolve directories in their config

**Comment by marijnh** [comment]
Sounds reasonable. Merged!

**Pull request merged**
